- name: bin directory
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/bin"
    state: directory

- name: Template to Run a test!
  ansible.builtin.template:
    src: demo_libei.sh.j2
    dest: "{{ ansible_env.HOME }}/bin/demo_libei.sh"
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    mode: '0755'