---
- name: Focus follow mouse
  community.general.dconf:
    key: "/org/gnome/desktop/wm/preferences/focus-mode"
    value: "'sloppy'"
    state: present

- name: Auto Raise
  community.general.dconf:
    key: "/org/gnome/desktop/wm/preferences/auto-raise"
    value: "true"
    state: present

- name: Auto Raise Delay
  community.general.dconf:
    key: "/org/gnome/desktop/wm/preferences/auto-raise-delay"
    value: 0
    state: present